language: python
python:
  - "3.6"

# install dependencies
install:
  - python setup.py install
  - pip install black pytest-cov

# run tests
script:
  - pytest --cov=bayesian_hmm tests/
  - black --check ./bayesian_hmm ./tests -v
